spring.application.name=Hospital_Management

server.port=${PORT:2503}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Hospital}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

spring.ai.openai.api-key=${GROQ_API_KEY:your_groq_api_key_here}
